after_script:
- "./scripts/remove-key.sh"
before_script:
- "./scripts/add-key.sh"
branches:
  only:
  - master
  - development
osx_image: xcode10.1
language: swift
os: osx
xcode_project: TesTravis.xcodeproj
env:
  global:
  - |
      - APP_NAME="TesTravis"
      - 'DEVELOPER_NAME="iPhone Distribution: the digital cie (99J6CKC97H)"'
      - PROFILE_NAME="TestTravisApp"
      - IPA_NAME="TesTravis"
      - ARCHIVE_NAME="TesTravis_Dev"
  - secure: {azzdddfdsgnjkfgfjdkghfdgjk"'é'"éj('dfsdf('('"(,ngfgdfg}
  - secure: {azzdddfdsgnjkfgfjdkghffgfgjk"'é'"éj('dfsdf('('"(,ngfgdfg}
  - secure: {azzdddfdsgnjkfgfjsgfsgfdghgfghfdgjk"'é'"éj('dfsdf('('"(,ngfgdfg}
xcode_scheme: TesTravis
script:
- "./scripts/build.sh"
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone 8